[tool.black]
line-length = 120
target-version = ['py312']

[tool.coverage.report]
omit = ["setup.py", "conftest.py", "tests/*", "docs/*"]

[tool.pytest.ini_options]
minversion = "8.0"
addopts = "-s --doctest-modules"
log_level = "DEBUG"
log_cli = true
testpaths = ["tests", "src"]
pythonpath = ["src"]

[tool.pylint]
load-plugins = [
    'pylint.extensions.check_elif',
    'pylint.extensions.docstyle',
    'pylint.extensions.dunder',
    'pylint.extensions.eq_without_hash',
    'pylint.extensions.mccabe',
    'pylint.extensions.overlapping_exceptions',
    'pylint.extensions.private_import',
    ''
]
disable = ['C0115', 'C0116', 'W0718', 'R1705', 'R1720']
max-line-length = 135
